[world]
RANDOM_SEED = 0

FOOD_ABUNDANCE = 0.02
WATER_ABUNDANCE = 0.01
TREE_PROB = 0.1
SWEET_PROB = 0.01
RESOURCE_LOCATIONS_FILE = "resource_locations.json"
# RESOURCE_LOCATIONS_FILE = "resource_locations_bigger.json"
WIDTH = 42
HEIGHT = 42
N_AGENTS = 1

[agent]
INIT_FOOD = 0
INIT_WATER = 0
FOOD_ACQUIRE_RATE = 10
WATER_ACQUIRE_RATE = 10
FOOD_CONSUME_RATE = 1
WATER_CONSUME_RATE = 1
FOOD_MAX_INVENTORY = 100
WATER_MAX_INVENTORY = 100
FOOD_LOT_SIZE = 6
WATER_LOT_SIZE = 2
MAX_TRADE_LOTS = 1
INVENTORY_LEVEL_CRITICAL_LOW = 0
INVENTORY_LEVEL_LOW_MEDIUM = 10
INVENTORY_LEVEL_MEDIUM_HIGH = 50

[trade]
MAX_TRADE_DISTANCE = 2


[rl]
INIT_Q_VALUES = -10000.0
SARSA_N = 30
GAMMA = 0.99
ALPHA = 0.01
EPSILON = 0.01
