[simulation]
VERBOSITY = 2

[world]
N_STEPS = 30000
RANDOM_SEED = 0
LAND_PROP = 0.7
FOOD_ABUNDANCE = 0.1
WATER_ABUNDANCE = 0.1
TREE_PROB = 0.1
SWEET_PROB = 0.01
RESOURCE_LOCATIONS_FILE = "resource_locations.json"
# RESOURCE_LOCATIONS_FILE = "resource_locations_bigger.json"
# RESOURCE_LOCATIONS_FILE = "resource_locations_river.json"
WIDTH = 20
HEIGHT = 20
# WIDTH = 42
# HEIGHT = 42
N_AGENTS = 20
HAS_TRADING = true
# HAS_TRADING = false

[agent]
INIT_FOOD = 0
INIT_WATER = 0
FOOD_ACQUIRE_RATE = 20
WATER_ACQUIRE_RATE = 20
FOOD_CONSUME_RATE = 1
WATER_CONSUME_RATE = 1
FOOD_MAX_INVENTORY = 200
WATER_MAX_INVENTORY = 200

INVENTORY_LEVEL_CRITICAL_LOW = 0
INVENTORY_LEVEL_LOW_MEDIUM = 10
INVENTORY_LEVEL_MEDIUM_HIGH = 50
DISTANCE_LEVEL_CRITICAL_LOW = 2
DISTANCE_LEVEL_LOW_MEDIUM = 10
DISTANCE_LEVEL_MEDIUM_HIGH = 30

[trade]
MAX_TRADE_DISTANCE = 2
LOW_LOT_SIZE = 10
MEDIUM_LOT_SIZE = 30
HIGH_LOT_SIZE = 60

[rl]
INIT_Q_VALUES = -10000.0
SARSA_N = 60
GAMMA = 0.99
ALPHA = 0.01
EPSILON = 0.05
# MULTI_POLICY = false
MULTI_POLICY = true
SAVE_MODEL = true
LOAD_MODEL = true
MODEL_CHECKPOINT_FILE = "multiP_1__agents_20__trading_1__totalItr_40000.json"
