[simulation]
VERBOSITY = 1

[world]
N_STEPS = 2
RANDOM_SEED = 0
LAND_PROP = 0.7
# FOOD_ABUNDANCE = 0.1
# WATER_ABUNDANCE = 0.1
FOOD_ABUNDANCE = 0.0
WATER_ABUNDANCE = 0.0
TREE_PROB = 0.1
SWEET_PROB = 0.01
WIDTH = 6
HEIGHT = 6
N_AGENTS = 30
HAS_TRADING = true

[agent]
INIT_FOOD = 0
INIT_WATER = 0
FOOD_ACQUIRE_RATE = 10
WATER_ACQUIRE_RATE = 10
FOOD_CONSUME_RATE = 5
WATER_CONSUME_RATE = 5
FOOD_MAX_INVENTORY = 1000
WATER_MAX_INVENTORY = 1000
FOOD_LOT_SIZE = 1
WATER_LOT_SIZE = 1
MAX_TRADE_LOTS = 1
INVENTORY_LEVEL_CRITICAL_LOW = 0
INVENTORY_LEVEL_LOW_MEDIUM = 10
INVENTORY_LEVEL_MEDIUM_HIGH = 50
DISTANCE_LEVEL_CRITICAL_LOW = 2
DISTANCE_LEVEL_LOW_MEDIUM = 10
DISTANCE_LEVEL_MEDIUM_HIGH = 30

[trade]
MAX_TRADE_DISTANCE = 2
FOOD_MIN_INVENTORY_LEVEL = 0
WATER_MIN_INVENTORY_LEVEL = 0

[rl]
INIT_Q_VALUES = -10000.0
SARSA_N = 60
GAMMA = 0.99
ALPHA = 0.01
EPSILON = 0.01
MULTI_POLICY = false
