[world]
RANDOM_SEED = 0

FOOD_ABUNDANCE = 0.1
WATER_ABUNDANCE = 0.1
TREE_PROB = 0.1
SWEET_PROB = 0.01
RESOURCE_LOCATIONS_FILE = "resource_locations.json"
# RESOURCE_LOCATIONS_FILE = "resource_locations_bigger.json"
WIDTH = 42
HEIGHT = 42
N_AGENTS = 20

[agent]
INIT_FOOD = 0
INIT_WATER = 0
FOOD_ACQUIRE_RATE = 10
WATER_ACQUIRE_RATE = 10
FOOD_CONSUME_RATE = 1
WATER_CONSUME_RATE = 1
FOOD_MAX_INVENTORY = 100
WATER_MAX_INVENTORY = 100
